services:
  geo-city-api:
    image: geo-city-api:latest
    ports:
      - 15000:8080
    environment:
      DB_USERNAME: cities
      DB_PASSWORD: password
      JDBC_SOURCE: jdbc:mysql://mysql:3306/cities #cities is the database name
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: strong_password
      MYSQL_DATABASE: cities
      MYSQL_USER: cities
      MYSQL_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
